language: go
go: 1.8.x

services: docker
sudo: required

script:
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 -ldflags="-s -w" go build
  - docker build -t meteogroup/sqs-to-kafka:test .
  - test/test.sh
