language: go
go: 1.8.x

services: docker
sudo: required

script:
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w"
  - docker build -t meteogroup/sqs-to-kafka:test .
  - test/test.sh
